language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install: cd code
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
script: make
notifications:
  email:
    recipients: yuriy.solodkyy+travis.mach7@gmail.com
    on_success: change
    on_failure: always
