language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang++
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - g++-4.8
    - clang-3.6
    - libboost-dev
before_install: cd code
install:
  - if [[ "$CXX" == g++ ]];                                     then export CXX="g++-4.8"; fi
  - if [[ "$CXX" == clang++ && "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="clang++-3.6"; fi
before_script:
    - uname -a
    - printenv
    - which clang++
    - clang++ --version 2>&1 | grep clang
script: make --keep-going
notifications:
  email:
    recipients: yuriy.solodkyy+travis.mach7@gmail.com
    on_success: change
    on_failure: always
